spring.datasource.url=jdbc:h2:file:./mydb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
#debug=true
logging.level.root=WARN
spring.profiles.active=prod

custom.my1=Robert Lewandowski
custom.flag=false
custom.number=12