# Praca domowa konfiguraja do yamla


spring:
  datasource:
    url: jdbc:h2:file:./mydb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

logging:
  level:
    root: INFO

#debug: true

custom:
  flag: false
  number: 3

person:
  firST-name: MateuszMateuszMateusz
  lastName: Kowalski
  AGE: 35
  middle-name: Andrzej
  is-married: true
  birth-date: 2007-12-01
  duration: 60
  numbers:
    - 1
    - 1
    - 4
    - 5
  map:
    "[key*1]": true
    key2: false
  pet:
    name: Reksio
    color: black
  cats:
    - name: Tom
      color: red
    - name: Jerry
      color: brown

  config:
    appName: QuizApp
    defaultGender: MALE
    Languages:
      - EN
      - PL
      - DE
    metadata:
      theme: dark
      version: 1.0
    nestedConfig:
      groupName: Admin Group
      groupSize: 10
#  gender: X
#  address: warsaw


# actuator
management:
  endpoints:
#    access:
#      default: none
    web:
      exposure:
        include: "*"
        exclude:
  endpoint:
    shutdown:
      access: unrestricted
    heapdump:
      access: unrestricted
    env:
      show-values: always